# Generated by Django 4.2.11 on 2024-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, default='', help_text='Текст на отзива', verbose_name='Текст')),
                ('name', models.CharField(blank=True, default='', help_text='Име на автора на отзива', max_length=50, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Отзив',
                'verbose_name_plural': 'Отзиви',
            },
        ),
    ]
