# Generated by Django 4.2.11 on 2024-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Заглаввие на снимката', max_length=50, verbose_name='Заглавие')),
                ('show_num', models.IntegerField(default=1, help_text='Пореден номер при показване', verbose_name='Поредност')),
                ('photo', models.ImageField(upload_to='clients', verbose_name='Снимка')),
            ],
            options={
                'verbose_name': 'Стая',
                'verbose_name_plural': 'Стаи',
            },
        ),
    ]
