# Generated by Django 4.2.11 on 2024-05-03 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Име')),
                ('phone', models.CharField(default='', max_length=14, verbose_name='Телефон')),
                ('email', models.CharField(default='', max_length=50, verbose_name='e-mail')),
                ('checkin', models.DateField(auto_now=True, verbose_name='Дата на пристигане')),
                ('checkout', models.DateField(auto_now=True, verbose_name='Дата на напускане')),
                ('adults', models.IntegerField(default=0, verbose_name='Брой възрастни')),
                ('children', models.IntegerField(default=0, verbose_name='Брой деца')),
                ('note', models.TextField(blank=True, default='', verbose_name='Допълнителни изисквания')),
                ('new_appointment', models.BooleanField(default=True, verbose_name='Нова резервация')),
                ('rooms', models.IntegerField(default=0, verbose_name='Брой резервирани стаи')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(upload_to='rooms', verbose_name='Снимка'),
        ),
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(default=1, verbose_name='Номер на стая')),
                ('checkin', models.DateField(auto_now=True, verbose_name='Дата на пристигане')),
                ('checkout', models.DateField(auto_now=True, verbose_name='Дата на напускане')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment', verbose_name='Допълнителни изисквания')),
            ],
            options={
                'verbose_name': 'Резервирана стая',
                'verbose_name_plural': 'Резервирани стаи',
            },
        ),
    ]
