# Generated by Django 4.2.11 on 2024-05-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_alter_room_photo_bookedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment', verbose_name='Резервация'),
        ),
    ]
